### ISSUE TITLE
This webpage has a redirect loop

### ISSUE THREAD

**Issue by oroalej** [Shadowss/TravianZ-by-Shadow#65]
Hello, I'm experiencing this error when i try to go to  ` /login.php`. how can i fix this?

**Comment by Shadowss** [comment]
Use this version : https://github.com/Shadowss/TravianZ

**Comment by oroalej** [comment]
Can I ask what php version should i use?i am currently using PHP5.6.12

**Comment by Shadowss** [comment]
I use PHP Version 5.4.45
